/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javasound;

import java.awt.Color;
import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileFilter;
import java.io.FileReader;
import java.io.IOException;
import java.util.Arrays;
import java.util.Comparator;
import javax.sound.sampled.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;

/**
 *
 * @author 429321-8
 */
public class GUIJavaSound extends javax.swing.JFrame {
    private JavaSound js;
    private JavaSoundPlay jsN;
    ImageIcon imgTrue = new ImageIcon(getClass().getResource("/javasound/true.png"));
    ImageIcon imgFalse = new ImageIcon(getClass().getResource("/javasound/false.png"));
    private File curDir;
    /**
     * Creates new form GUIJavaSound
     */
    public GUIJavaSound() {
        initComponents();
        titleTextTwo.setVisible(false);
        jButton1.setVisible(false);
        directionTwo.setVisible(false);
        playButTwo.setVisible(false);
        stopButTwo.setVisible(false);
        butClose.setVisible(false);
        alertFilename.setVisible(false);
        alertBox.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        backPanel = new javax.swing.JPanel();
        titleText = new javax.swing.JLabel();
        recSetOne = new javax.swing.JLabel();
        filenameField = new javax.swing.JTextField();
        recSetTwo = new javax.swing.JLabel();
        dirField = new javax.swing.JTextField();
        alertFilename = new javax.swing.JLabel();
        recSetThree = new javax.swing.JLabel();
        boxDif = new javax.swing.JComboBox();
        alertBox = new javax.swing.JLabel();
        recSetFour = new javax.swing.JLabel();
        butRec = new javax.swing.JButton();
        butStop = new javax.swing.JButton();
        titleTextTwo = new javax.swing.JLabel();
        directionTwo = new javax.swing.JTextField();
        playButTwo = new javax.swing.JButton();
        stopButTwo = new javax.swing.JButton();
        butClose = new javax.swing.JButton();
        boxByte = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        topMenu = new javax.swing.JMenuBar();
        recordButMenu = new javax.swing.JMenu();
        playButMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleText.setText("Recording settings");

        recSetOne.setText("Filename ");

        filenameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filenameFieldMouseClicked(evt);
            }
        });
        filenameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filenameFieldKeyReleased(evt);
            }
        });

        recSetTwo.setText("Direction");

        dirField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dirFieldKeyReleased(evt);
            }
        });

        alertFilename.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        alertFilename.setForeground(new java.awt.Color(0, 153, 255));
        alertFilename.setText("The format of audio will be \"WAVE\" for default. Write a filename without extended.");

        recSetThree.setText("Dis-tion");

        boxDif.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "4000.0F", "8000.0F", "10000.0F", "16000.0F", "44100.0F", "64100.0F", "128000.0F", "164100.0F", "256100.0F", "384100.0F" }));
        boxDif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxDifMouseClicked(evt);
            }
        });

        alertBox.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        alertBox.setForeground(new java.awt.Color(51, 153, 255));
        alertBox.setText("If you have a low powerful computer that chose no more 44100 Hz");

        recSetFour.setText("Set bytes");

        butRec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javasound/recimg.png"))); // NOI18N
        butRec.setText("REC");
        butRec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butRecMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                butRecMouseReleased(evt);
            }
        });

        butStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javasound/stop.png"))); // NOI18N
        butStop.setEnabled(false);
        butStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butStopMouseClicked(evt);
            }
        });

        titleTextTwo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleTextTwo.setText("Play settings");

        directionTwo.setEnabled(false);
        directionTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                directionTwoMouseClicked(evt);
            }
        });

        playButTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javasound/play.png"))); // NOI18N
        playButTwo.setEnabled(false);
        playButTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                playButTwoMousePressed(evt);
            }
        });

        stopButTwo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javasound/stop.png"))); // NOI18N
        stopButTwo.setEnabled(false);
        stopButTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stopButTwoMouseClicked(evt);
            }
        });
        stopButTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButTwoActionPerformed(evt);
            }
        });

        butClose.setText("Close");
        butClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butCloseMouseClicked(evt);
            }
        });

        boxByte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "8", "16" }));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javasound/false.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javasound/false.png"))); // NOI18N

        jLabel3.setText("in Hz");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Status:");

        jLabel5.setText("Ready!");

        jButton1.setText("Browse file");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout backPanelLayout = new javax.swing.GroupLayout(backPanel);
        backPanel.setLayout(backPanelLayout);
        backPanelLayout.setHorizontalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backPanelLayout.createSequentialGroup()
                        .addComponent(titleText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butRec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butStop))
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backPanelLayout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(backPanelLayout.createSequentialGroup()
                                        .addComponent(directionTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1))
                                    .addGroup(backPanelLayout.createSequentialGroup()
                                        .addComponent(butClose)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(playButTwo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(stopButTwo))))
                            .addComponent(titleTextTwo)
                            .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backPanelLayout.createSequentialGroup()
                                    .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(backPanelLayout.createSequentialGroup()
                                            .addComponent(recSetOne, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(filenameField, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(backPanelLayout.createSequentialGroup()
                                            .addComponent(recSetTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(dirField, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(70, 70, 70)
                                    .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(backPanelLayout.createSequentialGroup()
                                            .addComponent(recSetThree)
                                            .addGap(28, 28, 28)
                                            .addComponent(boxDif, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel3))
                                        .addGroup(backPanelLayout.createSequentialGroup()
                                            .addComponent(recSetFour)
                                            .addGap(18, 18, 18)
                                            .addComponent(boxByte, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(17, 17, 17))
                                .addGroup(backPanelLayout.createSequentialGroup()
                                    .addComponent(alertFilename)
                                    .addGap(18, 18, 18)
                                    .addComponent(alertBox))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        backPanelLayout.setVerticalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleText)
                    .addComponent(butRec)
                    .addComponent(butStop)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recSetTwo)
                            .addComponent(dirField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recSetOne)
                            .addComponent(filenameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxByte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recSetFour))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(recSetThree)
                                .addComponent(boxDif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))))
                .addGap(3, 3, 3)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alertFilename, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alertBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleTextTwo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(directionTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playButTwo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stopButTwo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(butClose)))
        );

        recordButMenu.setText("Record");
        recordButMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recordButMenuMouseClicked(evt);
            }
        });
        topMenu.add(recordButMenu);

        playButMenu.setText("Play");
        playButMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playButMenuMouseClicked(evt);
            }
        });
        topMenu.add(playButMenu);

        setJMenuBar(topMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void playButMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButMenuMouseClicked
        titleText.setVisible(false);
        boxDif.setVisible(false);
        boxByte.setVisible(false);
        butRec.setVisible(false);
        butStop.setVisible(false);
        dirField.setVisible(false);
        filenameField.setVisible(false);
        recSetFour.setVisible(false);
        recSetOne.setVisible(false);
        recSetThree.setVisible(false);
        recSetTwo.setVisible(false);
        jLabel3.setVisible(false);
        jLabel2.setVisible(false);
        jLabel1.setVisible(false);
        alertBox.setVisible(false);
        alertFilename.setVisible(false);
        
         titleTextTwo.setVisible(true);
        jButton1.setVisible(true);
        directionTwo.setVisible(true);
        playButTwo.setVisible(true);
        stopButTwo.setVisible(true);
        butClose.setVisible(true);
    }//GEN-LAST:event_playButMenuMouseClicked

    private void recordButMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recordButMenuMouseClicked
        titleText.setVisible(true);
        boxDif.setVisible(true);
        boxByte.setVisible(true);
        butRec.setVisible(true);
        butStop.setVisible(true);
        dirField.setVisible(true);
        filenameField.setVisible(true);
        recSetFour.setVisible(true);
        recSetOne.setVisible(true);
        recSetThree.setVisible(true);
        recSetTwo.setVisible(true);
        jLabel3.setVisible(true);
        jLabel2.setVisible(true);
        jLabel1.setVisible(true);
        
        titleTextTwo.setVisible(false);
        jButton1.setVisible(false);
        directionTwo.setVisible(false);
        playButTwo.setVisible(false);
        stopButTwo.setVisible(false);
        butClose.setVisible(false);
    }//GEN-LAST:event_recordButMenuMouseClicked

    private void stopButTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButTwoActionPerformed
       
    }//GEN-LAST:event_stopButTwoActionPerformed

    private void butRecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butRecMouseClicked
       float descr;
       int byteVar;
       descr = Float.parseFloat((String)boxDif.getSelectedItem());
       byteVar = Integer.parseInt((String)boxByte.getSelectedItem());
       File outputFile =new File(dirField.getText() + filenameField.getText() + ".wav");
       AudioFormat audioFormat=new AudioFormat(AudioFormat.Encoding.PCM_SIGNED,descr,byteVar,2,4,descr,false);
       DataLine.Info info=new DataLine.Info(TargetDataLine.class,audioFormat);
       TargetDataLine targetDataLine=null;
       try
       {
           targetDataLine=(TargetDataLine)AudioSystem.getLine(info);
           targetDataLine.open(audioFormat);
       }
       catch(LineUnavailableException e)
       {
           System.out.println("unable to get a recording line"); //its for debuging
           e.printStackTrace();
           System.exit(1);
       }
       AudioFileFormat.Type targetType=AudioFileFormat.Type.WAVE;
       this.js=new JavaSound(targetDataLine,targetType,outputFile);
       js.start();
       System.out.println("Recording...");   //its for debuging
       butStop.setEnabled(true);
       
       alertBox.setVisible(false);
       alertFilename.setVisible(false);
       
    }//GEN-LAST:event_butRecMouseClicked

    private void butStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butStopMouseClicked
       butRec.setBackground(Color.white);
       jLabel5.setText("Ready!");
        js.stopRecording();
       System.out.println("Recording stopped"); //its for debuging
    }//GEN-LAST:event_butStopMouseClicked

    private void dirFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dirFieldKeyReleased
           if(dirField.getText().isEmpty())
                if(imgTrue!=null) jLabel1.setIcon(imgFalse);
                else jLabel1.setText("X");       
        else 
            {
                if(imgTrue!=null) jLabel1.setIcon(imgTrue);
                else jLabel1.setText("V");
            }   
    }//GEN-LAST:event_dirFieldKeyReleased

    private void filenameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filenameFieldMouseClicked
        alertFilename.setVisible(true);
    }//GEN-LAST:event_filenameFieldMouseClicked

    private void boxDifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxDifMouseClicked
        alertBox.setVisible(true);
    }//GEN-LAST:event_boxDifMouseClicked

    private void filenameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filenameFieldKeyReleased
        if(dirField.getText().isEmpty())
                if(imgTrue!=null) jLabel2.setIcon(imgFalse);
                else jLabel1.setText("X");       
        else 
            {
                if(imgTrue!=null) jLabel2.setIcon(imgTrue);
                else jLabel1.setText("V");
            } 
    }//GEN-LAST:event_filenameFieldKeyReleased

    private void butRecMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butRecMouseReleased
        butRec.setBackground(Color.red);
        jLabel5.setText("Recording...");
    }//GEN-LAST:event_butRecMouseReleased

    private void directionTwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_directionTwoMouseClicked
        
    }//GEN-LAST:event_directionTwoMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        playButTwo.setEnabled(true);
        stopButTwo.setEnabled(true);
        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int returnVal = fileChooser.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                this.curDir = fileChooser.getSelectedFile();
                
                directionTwo.setText(this.curDir.getAbsolutePath());
            } else {
                
            }
    }//GEN-LAST:event_jButton1MouseClicked

    private void stopButTwoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stopButTwoMouseClicked
       jsN.playSound(jLabel5.getText()).stop();
       jLabel5.setText("Ready!");
    }//GEN-LAST:event_stopButTwoMouseClicked

    private void butCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butCloseMouseClicked
        playButTwo.setEnabled(false);
        stopButTwo.setEnabled(false);
        directionTwo.setText("");
    }//GEN-LAST:event_butCloseMouseClicked

    private void playButTwoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playButTwoMousePressed
        try {
            File f = new File((String) directionTwo.getText());
            String[] split = f.getName().split("\\.");
            if(split.length ==0)  {
                 jLabel5.setText("No extend!");
                return;
            }
            switch(split[split.length-1])
          {  
            case "wav":
                String fileName = new String(f.getAbsolutePath());
                System.out.println("Playing - " + fileName);
                jLabel5.setText(fileName);
                jsN.playSound(fileName).join();
                
          
        }
        }
            catch (Exception ioe) {
            ioe.printStackTrace();
        }
    }//GEN-LAST:event_playButTwoMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIJavaSound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIJavaSound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIJavaSound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIJavaSound.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GUIJavaSound().setVisible(true);
                
            }
            
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertBox;
    private javax.swing.JLabel alertFilename;
    private javax.swing.JPanel backPanel;
    private javax.swing.JComboBox boxByte;
    private javax.swing.JComboBox boxDif;
    private javax.swing.JButton butClose;
    private javax.swing.JButton butRec;
    private javax.swing.JButton butStop;
    private javax.swing.JTextField dirField;
    private javax.swing.JTextField directionTwo;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JTextField filenameField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu playButMenu;
    private javax.swing.JButton playButTwo;
    private javax.swing.JLabel recSetFour;
    private javax.swing.JLabel recSetOne;
    private javax.swing.JLabel recSetThree;
    private javax.swing.JLabel recSetTwo;
    private javax.swing.JMenu recordButMenu;
    private javax.swing.JButton stopButTwo;
    private javax.swing.JLabel titleText;
    private javax.swing.JLabel titleTextTwo;
    private javax.swing.JMenuBar topMenu;
    // End of variables declaration//GEN-END:variables
}
